on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    secrets:
      REGISTRY_LOGIN_SERVER:
        required: true
#      repository_name:
#        required: true
#        type: string
#      sha:
#        required: true
#        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called Container Security
  container_security:
    name: Container Security
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Scan the image
        uses: aquasecurity/trivy-action@master
        with:
        image-ref: '${{github.event.inputs.REGISTRY_LOGIN_SERVER}}/${{github.event.inputs.repository_name}}:${{github.event.inputs.sha}}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'